### ISSUE TITLE
Make message text color more visible

### ISSUE THREAD

**Issue by subhajit20** [subhajit20/omegle-clone#1]
![Text color issue](https://github.com/subhajit20/omegle-clone/assets/99127578/c9433e03-5695-4bb3-8b93-01d239139077)

Message text colors are not enough visible.
Try to add a deep green color and a deep orange color instead.

Go through this project setup guide:
[Project Setup guide](https://github.com/subhajit20/omegle-clone/blob/master/Readme.md)

If you need any further help feel free to tag me.
Thanks

**Comment by AntonyAsatiani** [comment]
Hi @subhajit20,
do we only need to change the text color here, or does it imply that we should also change the border colors?

**Comment by subhajit20** [comment]
Yes both text colour and border colour should be changed.
