### ISSUE TITLE
Add meaningful fav icon for this application

### ISSUE THREAD

**Issue by subhajit20** [subhajit20/omegle-clone#3]
Go through this project setup guide:
[Project Setup guide](https://github.com/subhajit20/omegle-clone/blob/master/Readme.md)

If you need any further help feel free to tag me.
Thanks

**Comment by rohit-chaware** [comment]
@subhajit20 I would like to work on this issue.

**Comment by subhajit20** [comment]
Assigned to you.
Thanks.
