### ISSUE TITLE
Remove History tab from Navbar

### ISSUE THREAD

**Issue by subhajit20** [subhajit20/omegle-clone#4]
Go through this project setup guide:
[Project Setup guide](https://github.com/subhajit20/omegle-clone/blob/master/Readme.md)

If you need any further help feel free to tag me.
Thanks

**Comment by JanisLacis5** [comment]
Hello, I want to understand correctly - do you want to just delete history tab link from navbar?

**Comment by subhajit20** [comment]
> Hello, I want to understand correctly - do you want to just delete history tab link from navbar?

Yes, just remove the link as of now.
Let me know if you would like to do this, will assign it to you.
Thanks

**Comment by JanisLacis5** [comment]
i'll do it

**Comment by subhajit20** [comment]
Assigned to you.
Thanks
