### ISSUE TITLE
Delete history page from the app folder

### ISSUE THREAD

**Issue by subhajit20** [subhajit20/omegle-clone#7]
![Screenshot 2023-11-25 at 6 49 12 PM](https://github.com/subhajit20/omegle-clone/assets/99127578/cbb1473a-17d1-4f1c-a697-4ead851bb066)

[History Folder link](https://github.com/subhajit20/omegle-clone/tree/master/frontend/src/app/history)

Go through this project setup guide:
[Project Setup guide](https://github.com/subhajit20/omegle-clone/blob/master/Readme.md)

If you need any further help feel free to tag me.
Thanks

**Comment by vinayakhegde1** [comment]
@subhajit20 hello bro can I work on this issue I would also contribute to the project :)

**Comment by subhajit20** [comment]
Hey @vinayakhegde1 sure.
Assigned to you.

**Comment by subhajit20** [comment]
Hey @vinayakhegde1 is there any updates?

**Comment by vinayakhegde1** [comment]
Sorry for the inconvenience I've don't have access to main machine for few days would update you as fast as possible

**Comment by subhajit20** [comment]
> Sorry for the inconvenience I've don't have access to main machine for few days would update you as fast as possible

Okay, take your time :)
